### ISSUE TITLE
Add readme file

### ISSUE THREAD

**Issue by ganzorig** [ganzorig/MeditationApp#20]

**Comment by BoldMIU** [comment]
Meditation Application for Android build from MIU students.

Version v1.1

Description

Our app created to help people reconnect with their self through mediation and multiple other healing practices.  
This app aims to be a 'GENO' for people, a safe space for them to relax and rejuvenate, taking a break for their vigorous and tiring daily life. 

GENO will  help the users enrich their mental well-being and enhance their lifestyle.

License: MIT

Source Code: https://github.com/ganzorig/MeditationApp
