### ISSUE TITLE
Make timestamp any of order in chat history.

### ISSUE THREAD

**Issue by norovoo** [ganzorig/MeditationApp#29]

**Comment by dhruvnagarajan** [comment]
Need more details @norovoo

**Comment by dhruvnagarajan** [comment]
Screenshots might help

**Comment by norovoo** [comment]
@dhruvnagarajan Sorry man, I was working on this. Next time I hope we will work on more complex solutions.

**Comment by dhruvnagarajan** [comment]
Cool @norovoo
